config/routes.rb
Rails.application.routes.draw do
  

  get "/home", to: "pages#home"

  root 'pages#home'
  resources :shipments
  resources :trips
  resources :users, except: [:new, :destroy] do
    resources :reviews, except: [:show, :index]
  end
  get "/register", to: "users#new"

  get "/login", to: "logins#new"
  post "/login", to: "logins#create"
  get "/logout", to: "logins#destroy"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
	belongs_to :user
	validates :user_id , presence: true
	validates :icountry, presence: true
    validates :istate, presence: true
    validates :icity, presence: true
    validates :iaddress, presence: true
    validates :izipcode, presence: true, numericality: true
	validates :fcountry, presence: true
    validates :fstate, presence: true
    validates :fcity, presence: true
    validates :faddress, presence: true
    validates :fzipcode, presence: true, numericality: true
	validates :day, presence: true, numericality: true, inclusion: {in: 1..31, message: "Enter valid date" }
	validates :month, presence: true, inclusion: { in: %w(January February March April May June July August September October November December),
													message: "Enter valid month name"}
	validates :year, presence: true, numericality: true, numericality: {greater_than_or_equal_to: 2015, message: "Enter valid year" }
	validates :maxweight, presence: true, numericality: true
	validates :maxheigth, presence: true, numericality: true
	validates :maxwidth, presence: true, numericality: true
	validates :maxlength, presence: true, numericality: true
	default_scope -> { order(updated_at: :desc) }


	def self.search(search)
		if search
			where(["icountry LIKE ? OR istate LIKE ? OR icity LIKE ? OR fcountry LIKE ? OR fcity LIKE ? OR fstate LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			all
		end

	end


	private
		def picture_size
			if picture.size > 3.megabytes
				errors.add(:picture, "should be less than 3 MB")
			end
		end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:edit, :update, :show]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update]

    def index
        @trips = Trip.search(params[:search]).paginate(page: params[:page], per_page: 5)
    end

    def new
      @trip = Trip.new
    end 

    def show
      
    end
   
   def create
      @trip = Trip.new(trip_params)
      @trip.user = current_user

      if @trip.save
        flash[:success] = "Oh yea! Your Trip were created succesfully!"
        redirect_to trips_path
      else
        render :new
      end
    end

    def edit
        
    end

    def update
        if @trip.update(trip_params)
            flash[:success] = "Your trip information was updated successfully!"
            redirect_to trip_path(@trip)
        else
            render :edit
        end
    end

    def destroy
        Trip.find(params[:id]).destroy
        flash[:success] = "Trip Deleted"
        redirect_to trips_path
    end



    private

        def trip_params
         params.require(:trip).permit(:icountry, :istate, :icity, :iaddress, :izipcode, :fcountry, :fstate, :fcity, :faddress, :fzipcode, :day, :month, :year, :maxweight, :maxheigth, :maxwidth, :maxlength)
        end

        def set_trip
            @trip = Trip.find(params[:id])
        end

        def require_same_user
            if logged_in?
                if current_user != @trip.user and !current_user.admin?
                    flash[:danger] = "You can only edit your own trips"
                    redirect_to root_path
                end
            else
                flash[:danger] = "You have to be logged in"
                redirect_to root_path  
            end
        end

end

app/views/trips/edit.html.erb
<p>
  <h1>Edit Trip</h1>
  <hr/>
</p>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@trip, html:{multipart:true}, validate: true) do |f| %>

      <h3>Initial Location</h3>

      <%= f.label :icountry, "Country" %><br />
      <%= f.country_select :icountry %><br /> 

      <%= f.label :istate, "State" %><br />
      <%= f.text_field :istate %><br /> 

      <%= f.label :icity, "City" %><br />
      <%= f.text_field :icity %><br /> 

      <%= f.label :iaddress, "Address" %><br />
      <%= f.text_field :iaddress %><br /> 

      <%= f.label :izipcode, "Zipcode" %><br />
      <%= f.text_field :izipcode %><br /> 

      <h3>Final Location</h3>

      <%= f.label :fcountry, "Country" %><br />
      <%= f.country_select :fcountry %><br /> 

      <%= f.label :fstate, "State" %><br />
      <%= f.text_field :fstate %><br /> 

      <%= f.label :fcity, "City" %><br />
      <%= f.text_field :fcity %><br /> 

      <%= f.label :faddress, "Address" %><br />
      <%= f.text_field :faddress %><br /> 

      <%= f.label :fzipcode, "Zipcode" %><br />
      <%= f.text_field :fzipcode %><br /> 

      <h3>Trip date</h3>

      <%= f.label :day, "Day" %><br />
      <%= f.text_field :day %><br /> 

      <%= f.label :month, "Month" %><br />
      <%= f.text_field :month %><br /> 

      <%= f.label :year, "Year" %><br />
      <%= f.text_field :year %><br /> 

      <h3>Accepted item parameters</h3>

      <%= f.label :maxweight, "Maximum weight (lbs)" %><br />
      <%= f.text_field :maxweight %><br /> 
     
      <%= f.label :maxwidth, "Maximum width (ft)" %><br />
      <%= f.text_field :maxwidth %><br /> 

      <%= f.label :maxlength, "Maximum length (ft)" %><br />
      <%= f.text_field :maxlength %><br />

      <%= f.label :maxheigth, "Maximum heigth (ft)" %><br />
      <%= f.text_field :maxheigth %><br /> 

      <%= f.submit 'Edit Trip', class: "btn btn-success" %>
    <% end %> 

  </div>
</div>

<script type="text/javascript">
  $("#trip_picture").bind("change", function(){
    size.in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 3){
      alert("Maximun file size is 3 Mb, please choose smaller file.")
    }
  });
</script>

app/views/trips/index.html.erb
<div class="search">
	<%= form_tag trips_path, :method => "get" do %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", class: "btn-success" %>
	<% end %>
</div>

<ul class= "nav nav-tabs">
	<li>
	<%= link_to "Shipments", shipments_path %>
	</li>
	<li class= 'active'>
	<%= link_to "Trips", trips_path %>
	</li>
</ul>

<div class="container">
<div class="table-responsive col-md-11">
<table>
		<tr id="firstrow">
			<th>Trip #</th>
			<th>Pick up at</th>
     		<th>Drop off at</th>
			<th>Date</th>
			<th>Carrier</th>
			<th>Updated</th>
		</tr>
		<% @trips.each do |trip| %>
			<tr>
				<td><%= link_to trip.id, trip_path(trip) %></td>
				<td><%= trip.icity %>, <%= trip.istate %>, <%= trip.icountry%></td>
				<td><%= trip.fcity %>, <%= trip.fstate %>, <%= trip.fcountry%></td>
				<td><%= trip.month%>-<%= trip.day%>-<%= trip.year%></td>
				<td>
					<section>
						<%= image_tag(trip.user.picture.url, size: "35", class: "picture") if trip.user.picture? %>
						<%= link_to [trip.user.lastname, trip.user.firstname].join(", "), user_path(trip.user) %>
					</section>
				</td>
        		<td><%= time_ago_in_words(trip.updated_at) %> ago</td>
			</tr>
		<% end %>
</table>
</div>
</div>

<center><%= will_paginate %></center>

app/views/trips/new.html.erb
<p>
  <h1>New Trip</h1>
  <hr/>
</p>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@trip, html:{multipart:true}, validate: true) do |f| %>

      <h3>Initial Location</h3>

      <%= f.label :icountry, "Country" %><br />
      <%= f.country_select :icountry %><br /> 

      <%= f.label :istate, "State" %><br />
      <%= f.text_field :istate %><br /> 

      <%= f.label :icity, "City" %><br />
      <%= f.text_field :icity %><br /> 

      <%= f.label :iaddress, "Address" %><br />
      <%= f.text_field :iaddress %><br /> 

      <%= f.label :izipcode, "Zipcode" %><br />
      <%= f.text_field :izipcode %><br /> 

      <h3>Final Location</h3>

      <%= f.label :fcountry, "Country" %><br />
      <%= f.country_select :fcountry %><br /> 

      <%= f.label :fstate, "State" %><br />
      <%= f.text_field :fstate %><br /> 

      <%= f.label :fcity, "City" %><br />
      <%= f.text_field :fcity %><br /> 

      <%= f.label :faddress, "Address" %><br />
      <%= f.text_field :faddress %><br /> 

      <%= f.label :fzipcode, "Zipcode" %><br />
      <%= f.text_field :fzipcode %><br /> 

      <h3>Trip date</h3>

      <%= f.label :day, "Day" %><br />
      <%= f.text_field :day %><br /> 

      <%= f.label :month, "Month" %><br />
      <%= f.text_field :month %><br /> 

      <%= f.label :year, "Year" %><br />
      <%= f.text_field :year %><br /> 

      <h3>Accepted item parameters</h3>

      <%= f.label :maxweight, "Maximum weight (lbs)" %><br />
      <%= f.text_field :maxweight %><br /> 
     
      <%= f.label :maxwidth, "Maximum width (ft)" %><br />
      <%= f.text_field :maxwidth %><br /> 

      <%= f.label :maxlength, "Maximum length (ft)" %><br />
      <%= f.text_field :maxlength %><br />

      <%= f.label :maxheigth, "Maximum heigth (ft)" %><br />
      <%= f.text_field :maxheigth %><br /> 

      <%= f.submit 'Create New Trip', class: "btn btn-success" %>
    <% end %> 

  </div>
</div>

<script type="text/javascript">
  $("#trip_picture").bind("change", function(){
    size.in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 3){
      alert("Maximun file size is 3 Mb, please choose smaller file.")
    }
  });
</script>

app/views/trips/show.html.erb
<div class= "row text-center">
  <p>
    <h1><%= @trip.icity %> to <%=@trip.fcity %></h1>
  </p>
  <hr>
  <div class= "col-md-4">
    <font1>&emsp;&emsp;&emsp;&emsp;Carrier Picture&emsp;&emsp;&emsp;&emsp;</font1><br><br>
    <div class="well image"><%= image_tag(@trip.user.picture, size: "200", class: "picture") if @trip.user.picture? %></div>
  </div>
  <div class= "col-md-4">
    <font1>&emsp;&emsp;&emsp;&emsp;Restrictions and Trip Date&emsp;&emsp;&emsp;&emsp;</font1><br><br>
    <dl class= "dl-horizontal text-left">
      <dt>Maximum Weight</dt><dd><%= @trip.maxweight %> lbs</dd>
      <dt>Maximum Height</dt><dd><%= @trip.maxheigth %> ft</dd>
      <dt>Maximum Width</dt><dd><%= @trip.maxwidth %> ft</dd>
      <dt>Maximum Length</dt><dd><%= @trip.maxlength %> ft</dd>
      <dt>Trip Date</dt><dd><%= @trip.month %> <%= @trip.day %>, <%= @trip.year %></dd>
    </dl>
  </div>
  <div class= "col-md-4">
    <font1>&emsp;&emsp;&emsp;Carrier Information&emsp;&emsp;&emsp;</font1><br><br>
    <dl class= "dl-horizontal text-left">
      <dt>Name</dt><dd><%= link_to [@trip.user.lastname, @trip.user.firstname].join(", "), user_path(@trip.user) %></dd>
      <dt>Email</dt><dd><%= @trip.user.email %></dd>
      <dt>Phone</dt><dd><%= @trip.user.phone %></dd>
      <dt>Comments</dt><dd><%= @trip.user.reviews.count %></dd>
    </dl>
  </div>
</div>
<hr>
<div class= "row text-center">
  <div class= "col-md-6 center  col-md-push-1">
    <font1>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Initial Location&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font1><br><br>
    <dl class= "dl-horizontal text-left col-md-offset-2">
      <dt>Address Line</dt><dd><%= @trip.iaddress %></dd>
      <dt>Address Line 2</dt><dd><%= @trip.icity %>, <%= @trip.istate %>, <%= @trip.icountry %> <%= @trip.izipcode %></dd>
    </dl>
  </div>
  <div class= "col-md-6 center col-md-pull-1">
    <font1>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Final Destination&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font1><br><br>
    <dl class= "dl-horizontal text-left col-md-offset-2">
      <dt>Address Line</dt><dd><%= @trip.faddress %></dd>
      <dt>Address Line 2</dt><dd><%= @trip.fcity %>, <%= @trip.fstate %>, <%= @trip.fcountry %> <%= @trip.fzipcode %></dd>
    </dl>
  </div>
  <br><small>Date Listed: <%= @trip.created_at %><br>
Date Updated: <%= @trip.updated_at %></small><br>

<h5 class="text-center">
  <% if logged_in? and @trip.user == current_user || current_user.admin? %>
    <%= link_to "Delete Trip", @trip, method: :Delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-small" %>
  <% end %>
  <% if logged_in? and @trip.user == current_user || current_user.admin? %>
    <%= link_to "Edit Trip", edit_trip_path, class: "btn btn-warning btn-small" %>
  <% end %>
  <%= link_to "Return to Trips Listing", trips_path, class: "btn btn-warning btn-small" %>
</h5>

</div>