config/routes.rb
Rails.application.routes.draw do
  

  get "/home", to: "pages#home"

  root 'pages#home'
  resources :shipments
  resources :trips
  resources :users, except: [:new, :destroy] do
    resources :reviews, except: [:show, :index]
  end
  get "/register", to: "users#new"

  get "/login", to: "logins#new"
  post "/login", to: "logins#create"
  get "/logout", to: "logins#destroy"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :shipments
	has_many :trips
	has_many :reviews, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :firstname, presence: true, length: { minimum: 2, maximum: 20 }
	validates :lastname, presence: true, length: { minimum: 2, maximum: 20 }
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
	                                uniqueness: { case_sensitive: false },
	                                format: { with: VALID_EMAIL_REGEX }
	validates :phone, presence: true, length: { minimum: 5, maximum: 20 }
	validates :role, inclusion: { in: %w(Customer Carrier),
													message: "Customer or Carrier"}
	validates :rating, numericality: true, inclusion: {in: 0..5, message: "should be in 0-5 range"}
	validates :password, :confirmation => true
	has_secure_password
	mount_uploader :picture, PictureUploader
	validate :picture_size
	default_scope -> { order(updated_at: :desc) }



	def self.search(search)
		if search
			where(["firstname LIKE ? OR lastname LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			all
		end

	end

	private
		def picture_size
			if picture.size > 3.megabytes
				errors.add(:picture, "should be less than 3 MB")
			end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_admin, only: [:index ]
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update]

    def index
        @users = User.search(params[:search]).paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Your account has been created successfully"
            session[:user_id] = @user.id
            redirect_to user_path(session[:user_id])
        else
            render :new
        end
    end

    def edit

    end

    def update
        if @user.update(user_params_edit)
            if @user.authenticate(params[:user][:pass]) || current_user.admin
                flash[:success] = "Your profile has been updated successfully"
                redirect_to user_path(@user)
            else
                flash[:danger] = "You entered wrong password"
                render :edit
            end
        else
            render :edit
        end
        #render plain: params[:user][:pass]
    end


    def show
        @reviews = Review.where(user_id: @user.id)
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User Deleted"
        redirect_to users_path
    end


    private

        def user_params
           params.require(:user).permit(:firstname, :lastname, :email, :phone, :password, :password_confirmation, :picture)
        end

        def user_params_edit
            params.require(:user).permit(:firstname, :lastname, :email, :phone, :picture)
        end

        def set_user
            @user = User.find(params[:id])
        end

        def require_same_user
            if current_user == nil
                flash[:danger] = "You have to be logged in"
                redirect_to root_path
            elsif current_user != @user and !current_user.admin?
                flash[:danger] = "You can only edit your own profile"
                redirect_to root_path
            end
        end

        def require_admin
            if current_user == nil
                flash[:danger] = "You have to be logged in"
                redirect_to root_path
            elsif !current_user.admin?
                flash[:danger] = "You are not allowed to view this page"
                redirect_to root_path
            end
        end

end

app/views/users/edit.html.erb
<p>
  <h1>Edit profile</h1>
  <hr/>
</p>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@user, html: { multipart:true }, validate: true) do |s| %>
      <%= s.label :firsname %><br />
      <%= s.text_field :firstname %><br />

      <%= s.label :lastname %><br />
      <%= s.text_field :lastname %><br />

      <%= s.label :email %><br />
      <%= s.email_field :email %><br />

      <%= s.label :phone %><br />
      <%= s.text_field :phone %><br />

      <%= s.label :pass, "Enter the Password"%><br />
      <%= s.password_field :pass %><br />

      <span class="picture">
            <%= s.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
          </span>

      <%= s.submit "Edit profile", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#user_picture").bind("change", function(){
    size.in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 3){
      alert("Maximun file size is 3 Mb, please choose smaller file.")
    }
  });
</script>

app/views/users/index.html.erb
<div class="search">
	<%= form_tag users_path, :method => "get" do %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", class: "btn-success" %>
	<% end %>
</div>

<div class="container">
<div class="table-responsive col-md-11">
<table >
		<tr id="firstrow">
			<th>Avatar</th>
			<th>First name</th>
			<th>Last name</th>
			<th>E-mail</th>
			<th>Phone number</th>
			<th>Role</th>
			<th>Rating</th>
			<th>Registration time</th>
			<th>Last update</th>
		</tr>
		<% @users.each do |user| %>
			<tr>
				<td>
					<section>
						<%= image_tag(user.picture.url, size: "35", class: "picture") if user.picture? %>
					</section>
				</td>
				<td><%= user.firstname%></td>
				<td><%= user.lastname%></td>
				<td><%= link_to user.email, user_path(user)%></td>
				<td><%= user.phone%></td>
				<td><%= user.role%></td>
				<td><%= user.rating%></td>
				<td><%= user.created_at.to_formatted_s(:long_ordinal)%></td>
				<td><%= user.updated_at.to_formatted_s(:long_ordinal)%></td>
			</tr>
		<% end %>
</table>
</div>
</div>
<center><%= will_paginate %></center>

app/views/users/new.html.erb
<p>
	<h1>New User Registration</h1>
	<hr/>
</p>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for(@user, html: { multipart:true }, validate: true) do |s| %>
			<%= s.label :firsname %><br />
			<%= s.text_field :firstname %><br />

			<%= s.label :lastname %><br />
			<%= s.text_field :lastname %><br />

			<%= s.label :email %><br />
			<%= s.email_field :email %><br />

			<%= s.label :phone %><br />
			<%= s.text_field :phone %><br />

			<%= s.label :password_confirmation, "Password"%><br />
			<%= s.password_field :password_confirmation %><br />

			<%= s.label :password, "Confirm Password"%><br />
			<%= s.password_field :password %><br />

			<span class="picture">
        		<%= s.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
      		</span>

			<%= s.submit "Register", class: "btn btn-success" %>
		<% end %>
	</div>
</div>



<script type="text/javascript">
	$("#user_picture").bind("change", function(){
		size.in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 3){
			alert("Maximun file size is 3 Mb, please choose smaller file.")
		}
	});
</script>

app/views/users/show.html.erb
<div class= "row text-center">
  <p>
    <h1><%= @user.firstname %> <%= @user.lastname %></h1>
  </p>
  <hr><br>
  <div class= "col-md-4 col-md-push-2">
    <font1>User Picture</font1><br><br>
    <%= image_tag(@user.picture.url,  class: "picture") if @user.picture? %>
  </div>
  <div class= "col-md-4 col-md-push-2">
    <font1>User Information</font1><br><br>
    <dl class= "dl-horizontal text-left">
      <dt>Email: </dt><dd><%= @user.email %></dd>
      <dt>Phone number: </dt><dd><%= @user.phone %></dd>
      <dt>Current role: </dt><dd><%= @user.role %></dd>
      <dt>Comments: </dt><dd><%= @user.reviews.count %></dd><br>
      <dt><small>Registered at </small></dt><dd><small><%= @user.created_at %></small></dd>
    </dl>
  </div>
</div>
<hr><br>

<div class= "row">
  <div class= "col-md-8 col-md-offset-2">
    <% if logged_in? and current_user != @user %>
      <%= link_to "Write a Review", new_user_review_path(@user), class: "btn btn-primary btn-small" %>
    <% end %> 
<br><br><br>

  <div class= "well"><br>
<% @reviews.each do |review| %>
  <p>Rating: <%= review.rating %></p>
  <p><%= simple_format(review.comment) %></p>
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Delete Review", [@user, review], method: :Delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-small" %>
  <% end %>
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Edit Review", edit_user_review_path(@user, review), class: "btn btn-warning btn-small" %>
  <% end %>
  <hr>
<% end %>
</div>
</div>
</div>