config/routes.rb
Rails.application.routes.draw do
  

  get "/home", to: "pages#home"

  root 'pages#home'
  resources :shipments
  resources :trips
  resources :users, except: [:new, :destroy] do
    resources :reviews, except: [:show, :index]
  end
  get "/register", to: "users#new"

  get "/login", to: "logins#new"
  post "/login", to: "logins#create"
  get "/logout", to: "logins#destroy"

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	belongs_to :user
	validates :user_id , presence: true
	validates :title, presence: true, length: { minimum: 2, maximum: 30}
	validates :pcountry, presence: true
	validates :pstate, presence: true
	validates :pcity, presence: true
	validates :paddress, presence: true
	validates :pzipcode, presence: true, numericality: true
	validates :dcountry, presence: true
	validates :dstate, presence: true
	validates :dcity, presence: true
	validates :daddress, presence: true
	validates :dzipcode, presence: true, numericality: true
	validates :weight, presence: true, numericality: true 
	validates :heigth, presence: true, numericality: true
	validates :length, presence: true, numericality: true
	validates :width, presence: true, numericality: true
	validates :delday, presence: true, numericality: true, inclusion: {in: 1..31, message: "Enter valid date" }
	validates :delmonth, presence: true, inclusion: { in: %w(January February March April May June July August September October November December),
													message: "Enter valid month name"}
	validates :delyear, presence: true, numericality: {greater_than_or_equal_to: 2015, message: "Enter valid year" }
	mount_uploader :picture, PictureUploader
	validate :picture_size
	default_scope -> { order(updated_at: :desc) }


	def self.search(search)
		if search
			where(["title LIKE ?", "%#{search}%"])
		else
			all
		end

	end

	private
		def picture_size
			if picture.size > 3.megabytes
				errors.add(:picture, "should be less than 3 MB")
			end
		end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
    before_action :set_shipment, only: [:edit, :update, :show]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update]

    def index
        @shipments = Shipment.search(params[:search]).paginate(page: params[:page], per_page: 5)
    end

    def show
        
    end

    def new
        @shipment = Shipment.new
    end

    def create
        @shipment = Shipment.new(shipment_params)
        @shipment.user = current_user

        if @shipment.save
            flash[:success] = "Your Shipment request has been submitted!"
            redirect_to shipments_path
        else
            render :new
        end
    end

     def edit
        
    end

    def update
        if @shipment.update(shipment_params)
            flash[:success] = "Your shipment was updated successfully!"
            redirect_to shipment_path
        else
            render :edit
        end
    end

    def destroy
        Shipment.find(params[:id]).destroy
        flash[:success] = "Shipment Deleted"
        redirect_to shipments_path
    end


    private

        def shipment_params
            params.require(:shipment).permit(:title, :pcountry, :pstate, :pcity, :paddress, :pzipcode, :dcountry, :dstate,
                                             :dcity, :daddress, :dzipcode, :weight, :heigth, :width, :length, :delday, 
                                             :delmonth, :delyear, :picture)
        end

        def set_shipment
            @shipment = Shipment.find(params[:id])
        end

        def require_same_user
            if current_user != @shipment.user and !current_user.admin?
                flash[:danger] = "You can only edit your own shipments"
                redirect_to shipments_path
            end
        end

end

app/views/shipments/edit.html.erb
<p>
	<h1>Edit Shipment</h1>
	<hr/>
</p>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for(@shipment, html: { multipart:true }, validate: true) do |s| %>
			<%= s.label :title %><br />
			<%= s.text_field :title %><br />

			<%= s.label :pcountry, "Pick Up: Country"%><br />
			<%= s.country_select :pcountry %><br />

			<%= s.label :pstate, "Pick Up: State" %><br />
			<%= s.text_field :pstate %><br />

			<%= s.label :pcity, "Pick Up: City" %><br />
			<%= s.text_field :pcity %><br />

			<%= s.label :paddress, "Pick Up: Address" %><br />
			<%= s.text_field :paddress %><br />

			<%= s.label :pzipcode, "Pick Up: Zip Code" %><br />
			<%= s.text_field :pzipcode %><br />

			<%= s.label :dcountry, "Drop Off: Country" %><br />
			<%= s.country_select :dcountry %><br />

			<%= s.label :dstate, "Drop Off: State" %><br />
			<%= s.text_field :dstate %><br />

			<%= s.label :dcity, "Drop Off: City" %><br />
			<%= s.text_field :dcity %><br />

			<%= s.label :daddress, "Drop Off: Address" %><br />
			<%= s.text_field :daddress %><br />

			<%= s.label :dzipcode, "Drop Off: Zip Code" %><br />
			<%= s.text_field :dzipcode %><br />

			<%= s.label :weight, "Weight (lbs)" %><br />
			<%= s.text_field :weight %><br />

			<%= s.label :width, "Width (ft)" %><br />
			<%= s.text_field :width %><br />

			<%= s.label :length, "Length (ft)" %><br />
			<%= s.text_field :length %><br />

			<%= s.label :heigth, "Height (ft)" %><br />
			<%= s.text_field :heigth %><br />

			<%= s.label :delday, "Delivery Day" %><br />
			<%= s.text_field :delday %><br />

			<%= s.label :delmonth, "Delivery Month" %><br />
			<%= s.text_field :delmonth %><br />

			<%= s.label :delyear, "Delivery Year" %><br />
			<%= s.text_field :delyear %><br />

			<span class="picture">
        		<%= s.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
      		</span>

			<%= s.submit "Edit Shipment", class: "btn btn-success" %>
		<% end %>
	</div>
</div>


<script type="text/javascript">
	$("#shipment_picture").bind("change", function(){
		size.in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 3){
			alert("Maximun file size is 3 Mb, please choose smaller file.")
		}
	});
</script>

app/views/shipments/index.html.erb
<div class="search">
	<%= form_tag shipments_path, :method => "get" do %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", class: "btn-success" %>
	<% end %>
</div>
<ul class= "nav nav-tabs">
	<li class= 'active'>
	<%= link_to "Shipments", shipments_path %>
	</li>
	<li>
	<%= link_to "Trips", trips_path %>
	</li>
</ul>



<div class="container">
<div class="table-responsive col-md-11">
<table>
		<tr id="firstrow">
			<th>Picture</th>
			<th>Title</th>
			<th>Pick up at</th>
			<th>Drop off at</th>
			<th>Customer</th>
			<th>Updated</th>
		</tr>
		<% @shipments.each do |shipment| %>
			<tr>
				<td>
					<%= image_tag(shipment.picture.url, size: "35", class: "picture") if shipment.picture? %>
				</td>
				<td><%= link_to shipment.title, shipment_path(shipment) %></td>
				<td><%= shipment.pcity %>, <%= shipment.pstate %>, <%= shipment.pcountry%></td>
				<td><%= shipment.dcity %>, <%= shipment.dstate %>, <%= shipment.dcountry%></td>
				<td>
					<section>
						<%= image_tag(shipment.user.picture.url, size: "35", class: "picture") if shipment.user.picture? %>
						<%= link_to [shipment.user.lastname, shipment.user.firstname].join(", "), user_path(shipment.user) %>
					</section>
				</td>
				<td> <%= time_ago_in_words(shipment.updated_at) %> ago</td>
			</tr>
		<% end %>
</table>
</div>
</div>
<center><%= will_paginate %></center>

app/views/shipments/new.html.erb
<p>
	<h1>New Shipment</h1>
	<hr/>
</p>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for(@shipment, html: { multipart:true }, validate: true) do |s| %>
			<%= s.label :title %><br />
			<%= s.text_field :title %><br />

			<%= s.label :pcountry, "Pick Up: Country"%><br />
			<%= s.country_select :pcountry %><br />

			<%= s.label :pstate, "Pick Up: State" %><br />
			<%= s.text_field :pstate %><br />

			<%= s.label :pcity, "Pick Up: City" %><br />
			<%= s.text_field :pcity %><br />

			<%= s.label :paddress, "Pick Up: Address" %><br />
			<%= s.text_field :paddress %><br />

			<%= s.label :pzipcode, "Pick Up: Zip Code" %><br />
			<%= s.text_field :pzipcode %><br />

			<%= s.label :dcountry, "Drop Off: Country" %><br />
			<%= s.country_select :dcountry %><br />

			<%= s.label :dstate, "Drop Off: State" %><br />
			<%= s.text_field :dstate %><br />

			<%= s.label :dcity, "Drop Off: City" %><br />
			<%= s.text_field :dcity %><br />

			<%= s.label :daddress, "Drop Off: Address" %><br />
			<%= s.text_field :daddress %><br />

			<%= s.label :dzipcode, "Drop Off: Zip Code" %><br />
			<%= s.text_field :dzipcode %><br />

			<%= s.label :weight, "Weight (lbs)" %><br />
			<%= s.text_field :weight %><br />

			<%= s.label :width, "Width (ft)" %><br />
			<%= s.text_field :width %><br />

			<%= s.label :length, "Length (ft)" %><br />
			<%= s.text_field :length %><br />

			<%= s.label :heigth, "Height (ft)" %><br />
			<%= s.text_field :heigth %><br />

			<%= s.label :delday, "Delivery Day" %><br />
			<%= s.text_field :delday %><br />

			<%= s.label :delmonth, "Delivery Month" %><br />
			<%= s.text_field :delmonth %><br />

			<%= s.label :delyear, "Delivery Year" %><br />
			<%= s.text_field :delyear %><br />

			<span class="picture">
        		<%= s.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
      		</span>

			<%= s.submit "Create Shipment", class: "btn btn-success" %>
		<% end %>
	</div>
</div>


<script type="text/javascript">
	$("#shipment_picture").bind("change", function(){
		size.in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 3){
			alert("Maximun file size is 3 Mb, please choose smaller file.")
		}
	});
</script>

app/views/shipments/show.html.erb
<div class= "row text-center">
	<p>
		<h1><%= @shipment.title %></h1>
	</p>
	<hr>
	<div class= "col-md-4">
		<font1>&emsp;&emsp;&emsp;&emsp;Item Picture&emsp;&emsp;&emsp;&emsp;</font1><br><br>
		<div class="well image"><%= image_tag(@shipment.picture.url, size: "200", class: "picture") if @shipment.picture? %></div>
	</div>
	<div class= "col-md-4">
		<font1>&emsp;&emsp;&emsp;&emsp;Item Information&emsp;&emsp;&emsp;&emsp;</font1><br><br>
		<dl class= "dl-horizontal text-left">
			<dt>Shipment Name</dt><dd><%= @shipment.title %></dd>
			<dt>Weight</dt><dd><%= @shipment.weight %> lbs</dd>
			<dt>Height</dt><dd><%= @shipment.heigth %> ft</dd>
			<dt>Width</dt><dd><%= @shipment.width %> ft</dd>
			<dt>Length</dt><dd><%= @shipment.length %> ft</dd>
			<dt>Delivery Date</dt><dd><%= @shipment.delmonth %> <%= @shipment.delday %>, <%= @shipment.delyear %></dd>
		</dl>
	</div>
	<div class= "col-md-4">
		<font1>&emsp;&emsp;&emsp;Customer Information&emsp;&emsp;&emsp;</font1><br><br>
		<dl class= "dl-horizontal text-left">
			<dt>Name</dt><dd><%= link_to [@shipment.user.lastname, @shipment.user.firstname].join(", "), user_path(@shipment.user) %></dd>
			<dt>Email</dt><dd><%= @shipment.user.email %></dd>
			<dt>Phone</dt><dd><%= @shipment.user.phone %></dd>
			<dt>Comments</dt><dd><%= @shipment.user.reviews.count %></dd>
		</dl>
	</div>
</div>
<hr>
<div class= "row text-center">
	<div class= "col-md-6 col-md-push-1">
		<font1>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Pickup Location&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font1><br><br>
		<dl class= "dl-horizontal text-left col-md-offset-2">
			<dt>Address Line</dt><dd><%= @shipment.paddress %></dd>
			<dt>Address Line 2</dt><dd><%= @shipment.pcity %>, <%= @shipment.pstate %>, <%= @shipment.pzipcode %>, <%= @shipment.pcountry %></dd>
		</dl>
	</div>
	<div class= "col-md-6 col-md-pull-1">
		<font1>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Drop-off Location&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;</font1><br><br>
		<dl class= "dl-horizontal text-left col-md-offset-2">
			<dt>Address Line</dt><dd><%= @shipment.daddress %></dd>
			<dt>Address Line 2</dt><dd><%= @shipment.dcity %>, <%= @shipment.dstate %>, <%= @shipment.dzipcode %>, <%= @shipment.dcountry %></dd>
		</dl>
	</div>

<br><small>Date Listed: <%= @shipment.created_at %><br>
Date Updated: <%= @shipment.updated_at %></small><br>

<br>

<h5 class="text-center">
	<% if logged_in? and @shipment.user == current_user || current_user.admin? %>
		<%= link_to "Delete Shipment", @shipment, method: :Delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-small" %>
	<% end %>
	<% if logged_in? and @shipment.user == current_user || current_user.admin? %>
		<%= link_to "Edit Shipment", edit_shipment_path, class: "btn btn-warning btn-small" %>
	<% end %>
	<%= link_to "Return to Shipments Listing", shipments_path, class: "btn btn-warning btn-small" %>
</h5>

</div>