config/routes.rb
Rails.application.routes.draw do
  

  get "/home", to: "pages#home"

  root 'pages#home'
  resources :shipments
  resources :trips
  resources :users, except: [:new, :destroy] do
    resources :reviews, except: [:show, :index]
  end
  get "/register", to: "users#new"

  get "/login", to: "logins#new"
  post "/login", to: "logins#create"
  get "/logout", to: "logins#destroy"

end

app/views/layouts/_footer.html.erb
<div class="wrapper">
	<div class="push">
		<div class="footer col-md-10 col-md-offset-1 well"><!--footer-->
      		<div class="row">
      			<p class="text-muted" style= "color: black"><small>Created by<strong style= "color: white">Yhlas Jorayev<strong style= "color: black">, <strong style= "color: white">Youngmin Kim<strong style= "color: black">, <strong style= "color: white">Jae Hyun Lee<strong style= "color: black">, <strong style= "color: white">Shenling Sun<strong style= "color: black">, <strong style= "color: white">Kun Li</strong></p></small>
			</div><!--/row-->
		</div>
	</div>
</div><!--/footer-->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top col-md-10 col-md-offset-1">

		<%= link_to "EzShip", root_path, class: "btn btn-success" , id: "logo" %>	
		
		<% if logged_in? %>
			
			<div class="nav-item">
				<ul class="dropdown">
					<%= link_to "#", class: "btn btn-default btn-primary dropdown-toggle", "data-toggle"=>"dropdown" do%>
						<%= current_user.firstname %><b class="caret"></b>
					<% end %>
					<ul class="dropdown-menu">
						<li><%= link_to "View Profile", user_path(current_user)%></li>
						<li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
						<li class="divider"></li>
						<li><%= link_to "Log Out", logout_path %></li>
					</ul>
				</ul>
			</div>
			<div class="nav-item">
				<%= link_to "New Trip Information", new_trip_path, class: "btn btn-default" %>
			</div>
			<div class="nav-item">
				<%= link_to "New Shipment Request", new_shipment_path, class: "btn btn-default" %>
			</div>
		<% else %>
			<div class="nav-item">
				<%= link_to "Log In", login_path, class: "btn btn-default" %>
			</div>
			<div class="nav-item">
				<%= link_to "Register", register_path, class: "btn btn-default " %>
			</div>
		<% end %>
		<div class="nav-item">
			<%= link_to "Trips", trips_path, class: "btn btn-default " %>
		</div>
		<div class="nav-item">
			<%= link_to "Shipments", shipments_path, class: "btn btn-default " %>
		</div>
		
</header>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %>
				<a class="close" data-dismiss="alert">&#215;</a>
			</div>
		<% end %>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EZShip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class=" col-md-10 col-md-offset-1 main">
    <%= render "layouts/header"%>
    <%= render "layouts/messages"%>
    <div id="content">
      <%= yield %>
    </div>
  </div>
  <%= render "layouts/footer"%>
</body>

</html>


<script type="text/javascript">
	$(document).ready(function(){
  		setTimeout(function(){
    		$('.alert').remove();
  		}, 5000);
 	})
</script>